# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
version: 2.1
executors:
  seurat_v5:
    docker:
      - image: agabriel/matk:v1.1
    working_directory: /tmp/workspace

jobs:
  build:
    executor: seurat_v5
    steps:
      - checkout
      - run:
          name: Get anndata input
          command: |
            python get_data/get_PBMC_dataset.py
      - persist_to_workspace:
          root: get_data
          paths:
            - pbmc.h5ad
  test:
    executor: seurat_v5
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Run tests
          command: |
              Rscript -e "reticulate::py_config(); .libPaths()"
              ls /tmp/workspace
              ls /tmp/workspace/get_data/
              MATK -t SuperCell -i /tmp/workspace/get_data/pbmc.h5ad -o MATK_output/SuperCell/pbmc/ -n 50 -f 2000 -k 30 -g 75 -s seurat
              MATK -t MetaCell -i /tmp/workspace/get_data/pbmc.h5ad -o MATK_output/SuperCell/pbmc/ -n 50 -f 2000 -k 30 -g 75 -s seurat
workflows:
  example:
    jobs:
      - build
      - test:
          requires:
            - build
