# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: agabriel/matk:v1.1
    steps:
      - checkout
      # Replace this with steps to build a package, or executable
      - run:
          name: Get anndata input
          command: 
            python get_data/get_PBMC_dataset.py
      - store_artifacts:
          path: get_data/pbmc.h5ad
  test:
    docker:
      - image: agabriel/matk:v1.1
    steps:
      - checkout
      # Replace this with a real test runner invocation
      - run:
          name: Run tests
          command: |
              Rscript -e "reticulate::py_config(); .libPaths()"
              MATK -t SuperCell -i get_data/pbmc.h5ad -o MATK_output/SuperCell/pbmc/ -n 50 -f 2000 -k 30 -g 75 -s seurat
              MATK -t MetaCell -i get_data/pbmc.h5ad -o MATK_output/SuperCell/pbmc/ -n 50 -f 2000 -k 30 -g 75 -s seurat
workflows:
  example:
    jobs:
      - build
      - test:
          requires:
            - build

